// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXXF7bcxsmyPluWK6OoiA-LSSrlYhcqWI',
    appId: '1:162993661553:web:1a41cb36e4f57c416a5dd0',
    messagingSenderId: '162993661553',
    projectId: 'grocery-d5de6',
    authDomain: 'grocery-d5de6.firebaseapp.com',
    storageBucket: 'grocery-d5de6.firebasestorage.app',
    measurementId: 'G-X401JE70BV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYdE1UATEDN_MDqhanSzdIUhbBMvYwTCA',
    appId: '1:162993661553:android:4cfd2466dda951666a5dd0',
    messagingSenderId: '162993661553',
    projectId: 'grocery-d5de6',
    storageBucket: 'grocery-d5de6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Z8AdqPlm3JxT12HIL33LaZlFUUjUp6M',
    appId: '1:162993661553:ios:7e537fbdf2cddff86a5dd0',
    messagingSenderId: '162993661553',
    projectId: 'grocery-d5de6',
    storageBucket: 'grocery-d5de6.firebasestorage.app',
    iosBundleId: 'com.grocery.adminApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Z8AdqPlm3JxT12HIL33LaZlFUUjUp6M',
    appId: '1:162993661553:ios:7e537fbdf2cddff86a5dd0',
    messagingSenderId: '162993661553',
    projectId: 'grocery-d5de6',
    storageBucket: 'grocery-d5de6.firebasestorage.app',
    iosBundleId: 'com.grocery.adminApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXXF7bcxsmyPluWK6OoiA-LSSrlYhcqWI',
    appId: '1:162993661553:web:77ed7a57f8ff40906a5dd0',
    messagingSenderId: '162993661553',
    projectId: 'grocery-d5de6',
    authDomain: 'grocery-d5de6.firebaseapp.com',
    storageBucket: 'grocery-d5de6.firebasestorage.app',
    measurementId: 'G-LC97J0KQ9K',
  );
}
