name: dealer_app
description: "GroceryGo Dealer Hub"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../packages/core
  models:
    path: ../../packages/models
  repository:
    path: ../../packages/repository
  ui_kit:
    path: ../../packages/ui_kit
  geocoding: ^3.0.0
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  provider: ^6.1.2
  go_router: ^14.6.1
  image_picker: ^1.0.4
  firebase_messaging: ^16.1.3
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
